### ISSUE TITLE
Create LargeHeading Component

### ISSUE THREAD

**Issue by borozcod** [sandalschurch/Year-In-Review#1]
Using the [tachyons](http://tachyons.io/) css framework. Create a LargeHeading component with an h1 tag.

- [x] Does the type resize for mobile?
- [x] Does it render children props?

Heading Example:
![issue-1](https://user-images.githubusercontent.com/9917633/41203524-1efd3ce6-6c8d-11e8-89dc-16aea7314f76.jpg)

**Comment by dierker** [comment]
Created pull request for this.
